language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 8
  - 9
script:
  - npm run test -- --coverage
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - npm install --no-save conventional-changelog-eslint
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
