language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 8
  - 9
script:
  - npm run test -- --coverage
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - npm install --no-save semantic-release semantic-release-tamia
  - >-
    npx travis-deploy-once "semantic-release --analyze-commits semantic-release-tamia/analyzeCommits --verify-release
    semantic-release-tamia/verifyRelease --generate-notes semantic-release-tamia/generateNotes"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
